### ISSUE TITLE
When scrolling start button being the strict limiter

### ISSUE THREAD

**Issue by Chessnl** [Dacaspex/Exhibit#107] opened 2019-05-16 09:20 UTC
When on the initial startup screen, there is a scrollbar, the furthest that can be scrolled is up to the point at which the start button fits just on the screen. It would be nicer if one could scroll a little further. (such that there basically is some empty red space under the start button.

![image](https://user-images.githubusercontent.com/34745596/57842279-7b77e700-77cc-11e9-9abe-8e28e104fc2a.png)

**Comment by Dacaspex** [comment] 2019-05-16 09:28
Duplicate of #100

**Closed by Dacaspex** 2019-05-16 09:28 UTC
Labels: UI, enhancement
